spring:
  application:
    name: ktu-document-management
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dms_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:your_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml # Points to your Liquibase file

app:
  storage:
    upload-dir: ./uploads